### ISSUE TITLE
distance method not completely correct

### ISSUE THREAD

**Issue by okovtun** [alcuritsin/OOP_CPP#1]
Функция огонь, метод - не совсем то :-(

**Comment by alcuritsin** [comment]
> Функция огонь, метод - не совсем то :-(

Я же говорил, не понятно, от какой точки измерять расстояние! На занятии, тогда будем исправлять `issue`! Я удивлен, что эти заработали. 🙂

**Comment by okovtun** [comment]
> > Функция огонь, метод - не совсем то :-(
> 
> Я же говорил, не понятно, от какой точки измерять расстояние! На занятии, тогда будем исправлять `issue`! Я удивлен, что эти заработали. 🙂

Ну надеюсь хоть сейчас разобрались))

**Comment by okovtun** [comment]
> > > Функция огонь, метод - не совсем то :-(
> > 
> > 
> > Я же говорил, не понятно, от какой точки измерять расстояние! На занятии, тогда будем исправлять `issue`! Я удивлен, что эти заработали. 🙂
> 
> Ну надеюсь хоть сейчас разобрались))

Кстати, ОТ какой точки, там все четенько, ошибка была в том, ДО какой точки считать)

**Comment by alcuritsin** [comment]
> > > Функция огонь, метод - не совсем то :-(
> > 
> > 
> > Я же говорил, не понятно, от какой точки измерять расстояние! На занятии, тогда будем исправлять `issue`! Я удивлен, что эти заработали. 🙂
> 
> Ну надеюсь хоть сейчас разобрались))

Мозг немного подкипает  🤯.

Сейчас-то конечно ясно! Когда всё по полочкам разложено.
